package it.contrader.dao;

import javax.transaction.Transactional;
import it.contrader.model.UserNotification;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

@Repository
@Transactional

/**
 * CrudRepository provides generic CRUD operation on a repository for a specific type. It has generic methods for CRUD operation.
 * @author gabriele
 *
 */

/** 
 * In this specific case we don't add any further method cause all the method we need are Insert/Delete.
 * These methods are already generated by crudRepository at runtime
 * @author gabriele
 *
 */
public interface UserNotificationRepository extends CrudRepository<UserNotification, Long>{

}
